name: Build post

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  execute:
    runs-on: ubuntu-latest
    concurrency: post-${{ github.ref }}
    env:
      ADS_DEV_KEY: ${{ secrets.ADS_DEV_KEY }}
    steps:
      - uses: adrn-blog/execute-post@main
        with:
          python-version: "3.10"
